name: mongaz
description: MONGAZ - Gas Order & Delivery Tracking
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^5.3.2
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^8.0.0
  flutter_map: ^8.2.0
  latlong2: ^0.9.1
  geolocator: ^9.0.2
  flutter_client_sse: ^2.0.3
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^19.3.1
  permission_handler: ^12.0.0+1
  sqflite: ^2.1.0
  workmanager: ^0.9.0+2
  intl: ^0.20.2
  logger: ^2.2.0
  toast: ^0.3.0
  intl_phone_number_input: ^0.7.4

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  mocktail: ^1.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Cormorant
      fonts:
        - asset: assets/fonts/CormorantGaramond.ttf
    - family: Cormorant-Italic
      fonts:
        - asset: assets/fonts/CormorantGaramond-Italic.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Thin.ttf
          weight: 100
        - asset: assets/fonts/Sora-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora-ExtraBold.ttf
          weight: 800
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon-mg.png"
  min_sdk_android: 21